# Generated by Django 3.0.6 on 2021-10-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
