# Generated by Django 3.0.6 on 2021-11-13 13:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lander', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WebDev', 'WebDev'), ('Software', 'Software'), ('Django', 'Django'), ('java', 'java'), ('python', 'python')], max_length=34),
        ),
    ]
