# Generated by Django 3.0.6 on 2021-11-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lander', '0002_auto_20211113_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
