# Generated by Django 3.0.6 on 2021-10-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lander', '0005_upvoteanswer_upvote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='upvote',
            new_name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='upvoteanswer',
            name='upvote_count',
        ),
    ]
