# Generated by Django 3.0.6 on 2021-10-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lander', '0006_auto_20211020_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvote_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lander.Answer'),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
