# Generated by Django 3.0.6 on 2021-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lander', '0007_auto_20211020_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvote_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='upvotequestion',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
